export const GENDER_ARRAY_Q1 = ['male', 'female'];
export const INCIDENCE_ARRAY_Q2 = ["rape","violence","humanTrafficking","childLabour","others"];
export const STATE_FIRST_LETTER_Q3 = [ "A-B","C-I","J-L","N-R","S-Z"];
export const STATE_ARRAY_1 = ["abia","adamawa", "akwaIbom", "anambra","bauchi","bayelsa","benue","borno"];
export const STATE_ARRAY_2 = [ "crossRiver","delta","ebonyi","edo","ekiti","enugu","gombe","imo"];
export const STATE_ARRAY_3 = ["jigawa","kaduna","kano","katsina","kebbi","kogi","kwara","lagos"];
export const STATE_ARRAY_4 = [ "nasarawa","niger","ogun","ondo","osun","oyo","plateau","rivers"];
export const STATE_ARRAY_5 = [ "sokoto","taraba","yobe","zamfara"];
export const GENDER_ARRAY_PATTERN = ['1', '2'];
export const INCIDENCE_ARRAY_PATTERN = /^[1-2]\*[1-5]$/; //i.e 3*2
export const STATE_FIRST_LETTER_PATTERN = /^[1-2]\*[1-5]\*[1-5]$/; // 3*2*4
export const STATE_ARRAY_PATTERN = /^[1-2]\*[1-5]\*[1-5]\*[1-8]$/; //i.e 3*2*3